//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ActivityNew
    {
        public DC_ActivityNew()
        {
            this.ORG_Employee = new HashSet<ORG_Employee>();
            this.DC_Resident = new HashSet<DC_Resident>();
        }
    
        public int ActivityNewID { get; set; }
        public int OrganizationID { get; set; }
        public string GANo { get; set; }
        public string GATitle { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string GAType { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Organizer { get; set; }
        public string Description { get; set; }
        public System.DateTime PStartTime { get; set; }
        public System.DateTime PEndTime { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> DelayStartTime { get; set; }
        public Nullable<System.DateTime> DelayEndTime { get; set; }
        public string Status { get; set; }
        public bool IsDelay { get; set; }
        public string Remark { get; set; }
        public string Result { get; set; }
        public string Process { get; set; }
        public string Summary { get; set; }
        public string Evaluation { get; set; }
        public string ResultRemark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<ORG_Employee> ORG_Employee { get; set; }
        public virtual ICollection<DC_Resident> DC_Resident { get; set; }
    }
}
