//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_Bill
    {
        public int BillID { get; set; }
        public int ResidentID { get; set; }
        public string BillNo { get; set; }
        public decimal TotalCpAmount { get; set; }
        public decimal TotalPayAmount { get; set; }
        public decimal TotalDiscountAmount { get; set; }
        public decimal TotalNeedAmount { get; set; }
        public string BillContent { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
