//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_CommodityItem
    {
        public int CommodityItemID { get; set; }
        public int OrganizationID { get; set; }
        public string CINo { get; set; }
        public string CIName { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> CICategory { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> OrderNum { get; set; }
    }
}
