//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_CheckRoom
    {
        public DC_CheckRoom()
        {
            this.DC_Armarium = new HashSet<DC_Armarium>();
            this.DC_CheckRoomQueueRec = new HashSet<DC_CheckRoomQueueRec>();
            this.DC_CheckRoomSch = new HashSet<DC_CheckRoomSch>();
        }
    
        public int CheckRoomID { get; set; }
        public int DeptID { get; set; }
        public string CheckRoomNo { get; set; }
        public string CheckRoomName { get; set; }
        public string CheckRoomDescription { get; set; }
        public string CheckRoomAddress { get; set; }
        public int Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DC_Armarium> DC_Armarium { get; set; }
        public virtual ICollection<DC_CheckRoomQueueRec> DC_CheckRoomQueueRec { get; set; }
        public virtual ICollection<DC_CheckRoomSch> DC_CheckRoomSch { get; set; }
    }
}
