//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_CheckRoomQueue
    {
        public int QueueID { get; set; }
        public int CheckRoomQueueRecID { get; set; }
        public int ServiceItemID { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string SIName { get; set; }
        public Nullable<int> CheckRoomID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int ResidentID { get; set; }
        public string ResidentName { get; set; }
        public string SerialNumber { get; set; }
        public int CheckNumber { get; set; }
        public int CheckStatus { get; set; }
        public Nullable<System.DateTime> CheckBeginTime { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual DC_CheckRoomQueueRec DC_CheckRoomQueueRec { get; set; }
        public virtual DC_ServiceItem DC_ServiceItem { get; set; }
        public virtual ORG_Employee ORG_Employee { get; set; }
        public virtual DC_Resident DC_Resident { get; set; }
        public virtual ORG_Organization ORG_Organization { get; set; }
    }
}
