//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_Family
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string Relation { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsEmerg { get; set; }
        public string Tell { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> HasKey { get; set; }
        public string Location { get; set; }
    }
}
