//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_GroupActivityCategory
    {
        public DC_GroupActivityCategory()
        {
            this.DC_GroupActivityItem = new HashSet<DC_GroupActivityItem>();
            this.DC_GroupActivityRecord = new HashSet<DC_GroupActivityRecord>();
        }
    
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DC_GroupActivityItem> DC_GroupActivityItem { get; set; }
        public virtual ICollection<DC_GroupActivityRecord> DC_GroupActivityRecord { get; set; }
    }
}
