//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_GroupActivityItem
    {
        public DC_GroupActivityItem()
        {
            this.DC_GroupActivityRecord = new HashSet<DC_GroupActivityRecord>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GroupActivityCategoryID { get; set; }
        public string ItemName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual DC_GroupActivityCategory DC_GroupActivityCategory { get; set; }
        public virtual ICollection<DC_GroupActivityRecord> DC_GroupActivityRecord { get; set; }
    }
}
