//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_Habit
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string HabitType { get; set; }
        public string Content { get; set; }
        public string Remarks { get; set; }
    }
}
