//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_MonitorTemplate
    {
        public DC_MonitorTemplate()
        {
            this.DC_MonitorItem = new HashSet<DC_MonitorItem>();
        }
    
        public int MonitorTemplateID { get; set; }
        public string MTNo { get; set; }
        public string MTName { get; set; }
        public string MTDescription { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DC_MonitorItem> DC_MonitorItem { get; set; }
    }
}
