//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_MonitorResult
    {
        public DC_MonitorResult()
        {
            this.DC_MonitorItem = new HashSet<DC_MonitorItem>();
        }
    
        public int MonitorResultID { get; set; }
        public int PersonID { get; set; }
        public string MRNo { get; set; }
        public Nullable<System.DateTime> MRDatetime { get; set; }
        public string SourceType { get; set; }
        public string SNO { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DC_MonitorItem> DC_MonitorItem { get; set; }
    }
}
