//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_Payment
    {
        public int PaymentID { get; set; }
        public int ResidentID { get; set; }
        public string PaymentNo { get; set; }
        public decimal Amount { get; set; }
        public string PayMethod { get; set; }
        public System.DateTime PayDate { get; set; }
        public string Payee { get; set; }
        public string InvoiceNo { get; set; }
        public string PayType { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
