//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ResidentServicePlan
    {
        public DC_ResidentServicePlan()
        {
            this.DC_ResidentServicePlanItem = new HashSet<DC_ResidentServicePlanItem>();
        }
    
        public int ResidentServicePlanID { get; set; }
        public int ResidentID { get; set; }
        public int ServiceGroupID { get; set; }
        public string SGNo { get; set; }
        public string SGName { get; set; }
        public decimal SumPrice { get; set; }
        public Nullable<System.DateTime> SStartDate { get; set; }
        public Nullable<System.DateTime> SEndDate { get; set; }
        public string Remark { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DC_ResidentServicePlanItem> DC_ResidentServicePlanItem { get; set; }
    }
}
