//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ResidentServicePlanItem
    {
        public int ResidentServicePlanItemID { get; set; }
        public int ResidentServicePlanID { get; set; }
        public int ServiceItemID { get; set; }
        public string SINo { get; set; }
        public string SIName { get; set; }
        public string SIType { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ServiceTimes { get; set; }
        public Nullable<int> RestTimes { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual DC_ResidentServicePlan DC_ResidentServicePlan { get; set; }
    }
}
