//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ServiceItem
    {
        public DC_ServiceItem()
        {
            this.DC_ChargeItem = new HashSet<DC_ChargeItem>();
            this.DC_CheckRoomQueue = new HashSet<DC_CheckRoomQueue>();
            this.DC_CheckRoomQueueRec = new HashSet<DC_CheckRoomQueueRec>();
            this.DC_CheckRoomSch = new HashSet<DC_CheckRoomSch>();
            this.DC_SerAppSerIt = new HashSet<DC_SerAppSerIt>();
            this.DC_SerGrpSerIt = new HashSet<DC_SerGrpSerIt>();
            this.DC_SerOrdSerIt = new HashSet<DC_SerOrdSerIt>();
        }
    
        public int ServiceItemID { get; set; }
        public int OrganizationID { get; set; }
        public int ServiceItemCategoryID { get; set; }
        public string SINo { get; set; }
        public string SIName { get; set; }
        public string Remark { get; set; }
        public string PhotoPath { get; set; }
        public string SIBelong { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> Priorit { get; set; }
        public Nullable<int> Hot { get; set; }
        public string Description { get; set; }
        public Nullable<int> SIExpenseType { get; set; }
        public string OrderMode { get; set; }
        public Nullable<float> Unit { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> SumPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> CostType { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string ServicePointOut { get; set; }
        public Nullable<decimal> UnitRoyaltyRate { get; set; }
        public Nullable<int> Status { get; set; }
        public string PinYinCode { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DC_ChargeItem> DC_ChargeItem { get; set; }
        public virtual ICollection<DC_CheckRoomQueue> DC_CheckRoomQueue { get; set; }
        public virtual ICollection<DC_CheckRoomQueueRec> DC_CheckRoomQueueRec { get; set; }
        public virtual ICollection<DC_CheckRoomSch> DC_CheckRoomSch { get; set; }
        public virtual ICollection<DC_SerAppSerIt> DC_SerAppSerIt { get; set; }
        public virtual ICollection<DC_SerGrpSerIt> DC_SerGrpSerIt { get; set; }
        public virtual ICollection<DC_SerOrdSerIt> DC_SerOrdSerIt { get; set; }
    }
}
