//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_SOSData
    {
        public int ID { get; set; }
        public string IMEI { get; set; }
        public Nullable<long> EmgDate { get; set; }
        public string Address { get; set; }
        public Nullable<float> Lat { get; set; }
        public Nullable<float> Lng { get; set; }
        public Nullable<float> Hpe { get; set; }
        public string Method { get; set; }
    }
}
