//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ServiceOrder
    {
        public DC_ServiceOrder()
        {
            this.DC_CheckRoomQueueRec = new HashSet<DC_CheckRoomQueueRec>();
        }
    
        public int ServiceOrderID { get; set; }
        public Nullable<int> ServiceAppID { get; set; }
        public int ResidentID { get; set; }
        public string SONo { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public string OrderTitle { get; set; }
        public string Priority { get; set; }
        public System.DateTime Otime { get; set; }
        public Nullable<int> PNCID { get; set; }
        public Nullable<decimal> InitPrice { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remark { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string ServiceAddress { get; set; }
        public Nullable<float> Lng { get; set; }
        public Nullable<float> Lat { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string Payment { get; set; }
        public string Delivery { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> SelEmployeeID { get; set; }
        public Nullable<int> ResidentServicePlanItemID { get; set; }
        public Nullable<bool> IsCancelFlag { get; set; }
        public string OrderType { get; set; }
        public string OrderFrom { get; set; }
        public Nullable<int> OrderCreator { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DC_CheckRoomQueueRec> DC_CheckRoomQueueRec { get; set; }
        public virtual DC_ServiceAppointment DC_ServiceAppointment { get; set; }
    }
}
