//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_SerAppSerIt
    {
        public int ServiceAppSIID { get; set; }
        public int ServiceAppID { get; set; }
        public int ServiceItemID { get; set; }
        public string SINo { get; set; }
        public string SIName { get; set; }
        public string SIType { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Qty { get; set; }
        public decimal SumPrice { get; set; }
        public Nullable<int> ResidentServicePlanItemID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> Priorit { get; set; }
    
        public virtual DC_ServiceAppointment DC_ServiceAppointment { get; set; }
        public virtual DC_ServiceItem DC_ServiceItem { get; set; }
    }
}
