//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_SerGrpSerIt
    {
        public int SerGrpSerItID { get; set; }
        public Nullable<int> ServiceItemID { get; set; }
        public Nullable<int> ServiceGroupID { get; set; }
        public int ServiceTimes { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual DC_ServiceGroup DC_ServiceGroup { get; set; }
        public virtual DC_ServiceItem DC_ServiceItem { get; set; }
    }
}
