//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_SerOrdSerIt
    {
        public int ServiceOrderSIID { get; set; }
        public int ServiceOrderID { get; set; }
        public int ServiceItemID { get; set; }
        public Nullable<int> ServiceSerialNo { get; set; }
        public string SINo { get; set; }
        public string SIName { get; set; }
        public string SIType { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Qty { get; set; }
        public decimal DiscountPrice { get; set; }
        public decimal SumPrice { get; set; }
        public Nullable<int> ResidentServicePlanItemID { get; set; }
        public Nullable<int> ChargeStatus { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> Priorit { get; set; }
    
        public virtual DC_ServiceItem DC_ServiceItem { get; set; }
    }
}
