//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ServiceAppointment
    {
        public DC_ServiceAppointment()
        {
            this.DC_SerAppSerIt = new HashSet<DC_SerAppSerIt>();
            this.DC_ServiceOrder = new HashSet<DC_ServiceOrder>();
        }
    
        public int ServiceAppID { get; set; }
        public Nullable<int> ResidentID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<int> PNCID { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public string ServiceItemType { get; set; }
        public string AppBy { get; set; }
        public Nullable<System.DateTime> AppTime { get; set; }
        public string AppPhone { get; set; }
        public string Relation { get; set; }
        public string Introducer { get; set; }
        public string IntroducerPhone { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DC_SerAppSerIt> DC_SerAppSerIt { get; set; }
        public virtual ICollection<DC_ServiceOrder> DC_ServiceOrder { get; set; }
    }
}
