//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_TaskChangeRecord
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ServiceTime { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsAudit { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public Nullable<int> TaskID { get; set; }
    
        public virtual DC_Task DC_Task { get; set; }
    }
}
