//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_Group
    {
        public ORG_Group()
        {
            this.ORG_Organization = new HashSet<ORG_Organization>();
            this.SYS_User = new HashSet<SYS_User>();
        }
    
        public int GroupID { get; set; }
        public string GroupNo { get; set; }
        public string GroupName { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<ORG_Organization> ORG_Organization { get; set; }
        public virtual ICollection<SYS_User> SYS_User { get; set; }
    }
}
