//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_Organization
    {
        public ORG_Organization()
        {
            this.DC_CheckRoomQueue = new HashSet<DC_CheckRoomQueue>();
            this.DC_PNC = new HashSet<DC_PNC>();
            this.SYS_User = new HashSet<SYS_User>();
        }
    
        public int OrganizationID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string OrgNo { get; set; }
        public string OrgName { get; set; }
        public string OrgType { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string HouseNumber { get; set; }
        public Nullable<float> Lng { get; set; }
        public Nullable<float> Lat { get; set; }
        public string LogoPath { get; set; }
        public Nullable<bool> IsPayFirstFlag { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DC_CheckRoomQueue> DC_CheckRoomQueue { get; set; }
        public virtual ICollection<DC_PNC> DC_PNC { get; set; }
        public virtual ORG_Group ORG_Group { get; set; }
        public virtual ICollection<SYS_User> SYS_User { get; set; }
    }
}
