//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_Employee
    {
        public ORG_Employee()
        {
            this.DC_CheckRoomQueue = new HashSet<DC_CheckRoomQueue>();
            this.DC_ActivityNew = new HashSet<DC_ActivityNew>();
        }
    
        public int EmployeeID { get; set; }
        public int OrganizationID { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string Nationality { get; set; }
        public string IdCard { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string HouseNumber { get; set; }
        public Nullable<float> Lng { get; set; }
        public Nullable<float> Lat { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string PhotoPath { get; set; }
        public string CensusAddressName { get; set; }
        public string Description { get; set; }
        public string ECPerson { get; set; }
        public string ECPhone { get; set; }
        public string Position { get; set; }
        public string JobTitle { get; set; }
        public string Qualifications { get; set; }
        public string Zip { get; set; }
        public string MerryFlag { get; set; }
        public string HiredType { get; set; }
        public string EmpState { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> CheckRoomID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DC_CheckRoomQueue> DC_CheckRoomQueue { get; set; }
        public virtual ICollection<DC_ActivityNew> DC_ActivityNew { get; set; }
    }
}
