//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_BaiDuAudioToken
    {
        public int TokenID { get; set; }
        public string TokenValue { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
