//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Function
    {
        public SYS_Function()
        {
            this.SYS_MenuFunction = new HashSet<SYS_MenuFunction>();
        }
    
        public int FunctionID { get; set; }
        public string FunctionNo { get; set; }
        public string FunctionName { get; set; }
        public string Url { get; set; }
        public string ModuleName { get; set; }
        public int OrderSeq { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public bool IsIndependent { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SYS_MenuFunction> SYS_MenuFunction { get; set; }
    }
}
