//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Role
    {
        public SYS_Role()
        {
            this.SYS_User = new HashSet<SYS_User>();
        }
    
        public int RoleID { get; set; }
        public string RoleNo { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public string DefaultPage { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SYS_User> SYS_User { get; set; }
    }
}
