//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MenuFunction
    {
        public int MenuFunctionID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string MenuName { get; set; }
        public int OrderSeq { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SYS_Function SYS_Function { get; set; }
        public virtual SYS_Menu SYS_Menu { get; set; }
    }
}
