//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Menu
    {
        public SYS_Menu()
        {
            this.SYS_MenuFunction = new HashSet<SYS_MenuFunction>();
        }
    
        public int MenuID { get; set; }
        public int RoleID { get; set; }
        public string MenuName { get; set; }
        public int OrderSeq { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SYS_MenuFunction> SYS_MenuFunction { get; set; }
    }
}
