//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_User
    {
        public SYS_User()
        {
            this.ORG_Group = new HashSet<ORG_Group>();
            this.ORG_Organization = new HashSet<ORG_Organization>();
            this.SYS_Role = new HashSet<SYS_Role>();
        }
    
        public int UserID { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<ORG_Group> ORG_Group { get; set; }
        public virtual ICollection<ORG_Organization> ORG_Organization { get; set; }
        public virtual ICollection<SYS_Role> SYS_Role { get; set; }
    }
}
